using System.Net;
using System.Net.Http;
using System.Text.Json;
using Playdeck.Core;
internal static class ReleaseTests {
 static string News(params (string Title,long Date)[] items)=>JsonSerializer.Serialize(new{appnews=new{appid=367520,newsitems=items.Select(x=>new{title=x.Title,date=x.Date,feedname="steam_community_announcements",url="https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/123"})}});
 sealed class Reply(string response,HttpStatusCode status=HttpStatusCode.OK):HttpMessageHandler {public int Count;public string Url="";protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,CancellationToken cancellationToken){Count++;Url=request.RequestUri!.ToString();return Task.FromResult(new HttpResponseMessage(status){Content=new StringContent(response)});}}
 public static async Task Run(Action<string,Action> test,Action<bool> assert,string root,bool network){
  var now=DateTimeOffset.UtcNow;long time=now.AddDays(-1).ToUnixTimeSeconds();string news=News(("Patch Version 1.5.12620 Now Live",time));
  Game Local()=>new(){Name="Local fixture",SteamId=367520,TrackPath=Path.Combine(root,"Standalone","game.exe"),VersionInfo=new(){Mode="Manual",ManualVersion="1.5.12459",ConfirmedReleaseSource="steam-news:367520"}};
  test("Release parser reads actual Steam CDN links and publisher labels",()=>{var c=ReleaseVersions.Parse(news,"steam-news:367520",now);assert(c.Items.Single().Version=="1.5.12620"&&ReleaseVersions.SafeLink(c.Items[0].Url));});
  test("Promotions, previews, consoles, dates and ambiguous labels are not release versions",()=>{foreach(var title in new[]{"Version 1.6 beta now available","Patch 2.0 coming soon","PlayStation Patch 1.9","Update 2026.09.12","Upgrade from 1.2 to 1.3","Sale 1.5 dollars","DLC version 2.0"})assert(ReleaseVersions.ExtractVersion(title)=="");});
  test("News response must match the requested identity",()=>{bool bad=false;try{ReleaseVersions.Parse(news,"steam-news:1",now);}catch(InvalidDataException){bad=true;}assert(bad);});
  test("Future announcements do not become released versions",()=>assert(ReleaseVersions.Parse(News(("Patch 9.9",now.AddDays(1).ToUnixTimeSeconds())),"steam-news:367520",now).Items.Count==0));
  string data=Path.Combine(root,"local-release");var handler=new Reply(news);
  using(var service=new GameVersions(handler)){
   var game=Local();var v=await service.Check(game,data,true);game.VersionInfo=v;var cached=await service.Check(game,data,true);
   test("Local manual version reaches official API without Steam installation or build",()=>assert(v.NeedsUpdate&&v.LatestVersion=="1.5.12620"&&v.InstalledBuild==""&&handler.Url.Contains("ISteamNews")));
   test("Repeated release checks reuse the daily cache",()=>assert(handler.Count==1&&cached.NeedsUpdate&&cached.NextReleaseCheckAt>now.AddHours(23)));
   var offline=await service.Check(game,data,false);test("Offline local refresh retains published release and known update",()=>assert(offline.NeedsUpdate&&offline.LatestVersion==v.LatestVersion&&handler.Count==1));
   game.VersionInfo.ManualVersion="1.5.12620";var matching=await service.Check(game,data,true);test("Changing only installed version recomputes a cached comparison",()=>assert(matching.MatchesLatest&&!matching.NeedsUpdate&&handler.Count==1));
   game.VersionInfo.ManualVersion="1.5.78.11833";var mismatch=await service.Check(game,data,true);test("Different numbering shapes never fabricate an ordered comparison",()=>assert(!mismatch.NeedsUpdate&&!mismatch.MatchesLatest&&mismatch.Status.Contains("numbering")));
   game=Local();game.VersionInfo.ConfirmedReleaseSource="";var unconfirmed=await service.Check(game,data,true);test("Unconfirmed edition still gets latest evidence but no misleading badge",()=>assert(unconfirmed.LatestVersion.Length>0&&!unconfirmed.NeedsUpdate&&unconfirmed.Status.Contains("Confirm")));
   game=Local();game.VersionInfo.ManualVersion="";var missing=await service.Check(game,data,true);test("Missing installed version does not block online release lookup",()=>assert(missing.LatestVersion.Length>0&&missing.Status.Contains("enter your installed")));
   string file=Path.Combine(root,"version.txt");File.WriteAllText(file,"1.5.12459");game=Local();game.VersionInfo.Mode="File";game.VersionInfo.EvidencePath=file;game.VersionInfo.InstalledConfirmed=true;var fromFile=await service.Check(game,data,true);test("Local version files compare with online releases",()=>assert(fromFile.NeedsUpdate&&fromFile.Source=="Confirmed version file"));
   game=Local();game.VersionInfo=v;game.VersionInfo.ReleaseAppId=10;game.VersionInfo=await service.Check(game,Path.Combine(root,"wrong-release"),false);test("Changing release identity discards unrelated latest evidence",()=>assert(game.VersionInfo.LatestVersion==""&&!game.VersionInfo.NeedsUpdate));
  }
  test("A newer unnumbered patch prevents stale numbered releases from claiming current",()=>{var c=ReleaseVersions.Parse(News(("Patch 1.5.12620",time),("Hotfix now live",time+100)),"steam-news:367520",now);var v=GameVersions.ReadLocal(Local());ReleaseVersions.Apply(v,c.Key,c);assert(v.NewerUnnumberedRelease&&!v.MatchesLatest&&!v.NeedsUpdate&&v.ReleaseTitle=="Hotfix now live");});
  test("Cached known updates remain yellow while expired matches need a check",()=>{var c=ReleaseVersions.Parse(news,"steam-news:367520",now);c.CheckedAt=now.AddDays(-2);var v=GameVersions.ReadLocal(Local());ReleaseVersions.Apply(v,c.Key,c);assert(VersionBadge.For(v,now).Color=="#F4D35D");v.NeedsUpdate=false;v.MatchesLatest=true;assert(VersionBadge.For(v,now).NeedsHelp);});
  var badHandler=new Reply("unavailable",HttpStatusCode.ServiceUnavailable);using(var service=new GameVersions(badHandler)){var one=await service.Check(Local(),Path.Combine(root,"release-failure"),true);var two=await service.Check(Local(),Path.Combine(root,"release-failure"),true);test("Failed release requests back off for a day and never pretend to compare",()=>assert(badHandler.Count==1&&one.ReleaseError.Length>0&&!two.MatchesLatest&&!two.NeedsUpdate&&two.NextReleaseCheckAt>now.AddHours(23)));}
  using(var service=new GameVersions(new Reply(news))){var tool=Local();tool.IsTool=true;var v=await service.Check(tool,Path.Combine(root,"tool-release"),true);test("Tools perform no release lookup or installed scan",()=>assert(ReferenceEquals(v,tool.VersionInfo)));}
  string github=JsonSerializer.Serialize(new[]{new{tag_name="v1.10.0",name="Stable release",draft=false,prerelease=false,published_at=now.AddDays(-2),html_url="https://github.com/example/game/releases/tag/v1.10.0"},new{tag_name="v2.0.0",name="Preview",draft=false,prerelease=true,published_at=now.AddDays(-1),html_url="https://github.com/example/game/releases/tag/v2.0.0"}});
  test("GitHub releases exclude previews and bind links to the chosen repository",()=>{var c=ReleaseVersions.Parse(github,"github:example/game",now);assert(c.Items.Count==1&&c.Items[0].Version=="1.10.0");assert(ReleaseVersions.Parse(github,"github:other/game",now).Items.Count==0);assert(ReleaseVersions.Repository("https://github.com/example/game/")=="example/game");assert(ReleaseVersions.Repository("../secret")=="");});
  using(var service=new GameVersions(new Reply(github))){var game=new Game{VersionInfo=new(){Mode="Manual",ManualVersion="1.9.0",GitHubRepository="example/game",ConfirmedReleaseSource="github:example/game"}};var v=await service.Check(game,Path.Combine(root,"github-release"),true);test("Games without any Steam identity compare through GitHub",()=>assert(v.NeedsUpdate&&v.AppId==0&&v.LatestVersion=="1.10.0"));}
  if(network){using var service=new GameVersions();var v=await service.Check(Local(),Path.Combine(root,"live-local-release"),true);test("Live local-game comparison fetches human release labels without a manifest",()=>assert(v.ReleaseCheckedAt.HasValue&&v.LatestVersion.Length>0&&v.ReleaseUrl.Length>0&&(v.NeedsUpdate||v.MatchesLatest)));}
 }
 public static async Task Audit(string libraryFile,string output){
  var library=JsonSerializer.Deserialize<Library>(File.ReadAllText(libraryFile),Store.Json)!;
  var games=library.Games.Where(g=>!g.Removed&&!g.Archived&&!g.IsTool).ToArray();using var service=new GameVersions();int checkedCount=0,numbered=0,errors=0,installed=0,shapes=0;
  foreach(var game in games){var v=await service.Check(game,output,true);checkedCount++;if(v.ReleaseError.Length>0)errors++;if(v.LatestVersion.Length>0)numbered++;if(v.LocalAvailable&&v.Installed.Length>0)installed++;if(v.LocalAvailable&&v.LatestVersion.Length>0&&GameVersions.CompareLabels(v.Installed,v.LatestVersion)!=null)shapes++;Console.WriteLine($"Audited {checkedCount}/{games.Length}; release labels {numbered}; errors {errors}");}
  Store.Atomic(Path.Combine(output,"coverage.json"),new{ActiveGames=games.Length,NumberedReleaseFound=numbered,InstalledEvidenceFound=installed,NumericLabels=shapes,ProviderErrors=errors,Note="Read-only real-library audit. Source and installed-version confirmation are still required; counts are evidence availability, not verified comparisons."});
 }
}
