using System;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Playdeck.Core;
internal static partial class VersionTests {
 public static async Task Run(Action<string,Action> test,Action<bool> assert,string root,bool network){
  test("Version ordering handles numeric segments and prereleases",()=>{assert(GameVersions.CompareLabels("1.9","1.10")>0);assert(GameVersions.CompareLabels("v1.2.0-beta.2","1.2.0-beta.11")>0);assert(GameVersions.CompareLabels("1.2.0-beta","1.2.0")>0);assert(GameVersions.CompareLabels("1.2.0","1.2.0-beta")<0);assert(GameVersions.CompareLabels("1.2+abc","1.2+def")==0);assert(GameVersions.CompareLabels("release-final","release-next")==null);});
  test("VDF supports comments, escaped paths and quoted braces",()=>{var v=VdfNode.Parse("// comment\n\"AppState\" { \"path\" \"C:\\\\Games\" \"name\" \"{\" }");assert(v.Node("AppState")!.Text("name")=="{"&&v.Node("AppState")!.Text("path")==@"C:\Games");});
  test("Malformed VDF fails without partial results",()=>{bool failed=false;try{VdfNode.Parse("\"AppState\" { \"buildid\" \"100\"");}catch(InvalidDataException){failed=true;}assert(failed);});
  string directory=Path.Combine(root,"version-fixture");Directory.CreateDirectory(directory);string manifest=Path.Combine(directory,"appmanifest_480.acf");File.WriteAllText(manifest,"\"AppState\" { \"appid\" \"480\" \"buildid\" \"100\" \"StateFlags\" \"4\" \"UserConfig\" { \"BetaKey\" \"beta\" } }");var game=new Game{SteamId=480,VersionInfo=new(){ManifestPath=manifest}};
  test("Steam manifest preserves app, installed build and beta branch",()=>{var v=GameVersions.ReadLocal(game,Array.Empty<string>());assert(v.AppId==480&&v.InstalledBuild=="100"&&v.Branch=="beta"&&v.InstallationReady);});
  test("Wrong AppID cannot borrow an installed build",()=>{var wrong=new Game{SteamId=481,VersionInfo=new(){ManifestPath=manifest}};var v=GameVersions.ReadLocal(wrong,Array.Empty<string>());assert(v.InstalledBuild==""&&v.Status=="Manifest AppID mismatch");});
  test("Manual values do not become Steam build IDs",()=>{var manual=new Game{SteamId=480,VersionInfo=new(){Mode="Manual",ManualVersion="1.9",ManualLatest="1.10"}};var v=GameVersions.ReadLocal(manual);assert(v.NeedsUpdate&&v.InstalledBuild==""&&v.Source=="Manual entry");});
  string response="{\"status\":\"success\",\"data\":{\"480\":{\"depots\":{\"branches\":{\"public\":{\"buildid\":\"300\"},\"beta\":{\"buildid\":\"200\"},\"secret\":{\"buildid\":\"400\",\"pwdrequired\":\"1\"}}}}}}";
  test("Remote parser binds AppID and excludes protected branches",()=>{var cache=GameVersions.ParseRemote(response,480,DateTimeOffset.UtcNow);assert(cache.Branches["beta"]=="200"&&!cache.Branches.ContainsKey("secret"));bool failed=false;try{GameVersions.ParseRemote(response,481,DateTimeOffset.UtcNow);}catch(InvalidDataException){failed=true;}assert(failed);});
  test("Missing archived source retains its last known version",()=>{var archived=new Game{Archived=true,TrackPath=Path.Combine(directory,"missing.exe"),VersionInfo=new(){Installed="1.2.3",Source="Executable metadata",LocalPath=Path.Combine(directory,"missing.exe"),ObservedAt=DateTimeOffset.UtcNow.AddDays(-5)}};var v=GameVersions.ReadLocal(archived,Array.Empty<string>());assert(v.Installed=="1.2.3"&&!v.LocalAvailable&&v.Status.Contains("last known")&&!v.NeedsUpdate);});
  test("Removed automatic Steam manifest retains bound evidence only",()=>{var lost=new Game{SteamId=480,TrackPath=Path.Combine(directory,"gone.exe"),VersionInfo=new(){AppId=480,Installed="Build 100",InstalledBuild="100",Source="Steam app manifest",LocalPath=Path.Combine(directory,"gone.acf"),EvidenceExecutable=Path.Combine(directory,"gone.exe")}};var v=GameVersions.ReadLocal(lost,Array.Empty<string>());assert(v.InstalledBuild=="100"&&!v.LocalAvailable&&!v.NeedsUpdate);lost.TrackPath=Path.Combine(directory,"different.exe");assert(GameVersions.ReadLocal(lost,Array.Empty<string>()).InstalledBuild=="");});
  var handler=new Reply(response);using(var service=new GameVersions(handler)){var first=await service.Check(game,directory,true);var second=await service.Check(game,directory,true);test("Version checks compare the installed branch and reuse cached responses",()=>assert(first.LatestBuild=="200"&&first.NeedsUpdate&&second.NeedsUpdate&&handler.Count==1));}
  string cachePath=Path.Combine(directory,"version-cache","480.json");var cacheData=new BuildCache{AppId=480,CheckedAt=DateTimeOffset.UtcNow.AddDays(-2),RetryAfter=DateTimeOffset.MinValue,Branches=new(){{"beta","200"}}};Store.Atomic(cachePath,cacheData);var bad=new Reply("unavailable",HttpStatusCode.ServiceUnavailable);using(var service=new GameVersions(bad)){var first=await service.Check(game,directory,true);var second=await service.Check(game,directory,true);test("Failed lookups preserve evidence and back off without false update claims",()=>assert(first.LatestBuild=="200"&&first.Status=="Online check unavailable"&&!first.NeedsUpdate&&second.RemoteCheckedAt.HasValue&&bad.Count==1));}
  string incomplete=Path.Combine(directory,"incomplete.acf");File.WriteAllText(incomplete,File.ReadAllText(manifest).Replace("\"StateFlags\" \"4\"","\"StateFlags\" \"0\""));using(var service=new GameVersions(new Reply(response))){var v=await service.Check(new Game{SteamId=480,VersionInfo=new(){ManifestPath=incomplete}},Path.Combine(directory,"incomplete"),true);test("Incomplete Steam installation never reports an available update",()=>assert(!v.NeedsUpdate&&v.Status=="Steam installation is incomplete"));}
  if(network){string liveManifest=Path.Combine(directory,"live.acf");File.WriteAllText(liveManifest,"\"AppState\" { \"appid\" \"367520\" \"buildid\" \"1\" \"StateFlags\" \"4\" }");using var liveService=new GameVersions();var live=await liveService.Check(new Game{SteamId=367520,VersionInfo=new(){ManifestPath=liveManifest}},Path.Combine(directory,"live"),true);test("Live provider returns a public Steam build with dated evidence",()=>assert(live.LatestBuild.Length>0&&live.RemoteCheckedAt.HasValue&&live.Branch=="public"));}
  using(var service=new GameVersions(new Reply(response))){var offline=await service.Check(game,directory,false);test("Offline checks retain local version without remote comparison",()=>assert(offline.InstalledBuild=="100"&&offline.LatestBuild==""&&!offline.NeedsUpdate));}
 }
 sealed class Reply(string response,HttpStatusCode status=HttpStatusCode.OK):HttpMessageHandler {public int Count;protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,CancellationToken cancellationToken){Count++;return Task.FromResult(new HttpResponseMessage(status){Content=new StringContent(response)});}}
}
