using System;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Media;
using Playdeck.Core;
namespace Playdeck;
public sealed partial class MainWindow {
 int activityDays=30;
 static readonly string[] ChartColors={"#E1FF46","#FF957F","#76DCCB","#B1A0E5","#F3CD66","#88A0CE"};
 Border StatsPanel(string title,string caption,UIElement child){var stack=new StackPanel();var head=new Border{Background=Checker(),CornerRadius=new CornerRadius(14,14,0,0),Padding=new Thickness(20,15,20,13)};head.Child=Text(title,22,"#F2F0E9",FontWeights.Black);stack.Children.Add(head);var body=new StackPanel{Margin=new Thickness(20,16,20,20)};if(caption.Length>0){var t=Text(caption,12,"#AAA8AF");t.Margin=new Thickness(0,0,0,16);body.Children.Add(t);}body.Children.Add(child);stack.Children.Add(body);return new Border{Background=Brush("#242427"),BorderBrush=Brush("#3C3C41"),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(16),Child=stack};}
 void Activity(){
  var report=ActivityReport.Build(library.Games,sessions,activityDays,DateTime.Today);var ninety=ActivityReport.Build(library.Games,sessions,90,DateTime.Today);
  var heading=new DockPanel{Margin=new Thickness(0,0,0,18)};var tools=new WrapPanel{HorizontalAlignment=HorizontalAlignment.Right,VerticalAlignment=VerticalAlignment.Center};DockPanel.SetDock(tools,Dock.Right);heading.Children.Add(tools);
  foreach(int days in new[]{7,30,90}){int value=days;var button=Btn(days+" DAYS",()=>{activityDays=value;libraryScroll.ScrollToTop();Render();},days==activityDays);button.Margin=new Thickness(6,0,0,0);button.MinWidth=78;button.Padding=new Thickness(12,8,12,8);tools.Children.Add(button);}var refresh=Btn("",()=>{if(!demo)sessions=Store.Sessions(root);Render();});refresh.Content=new System.Windows.Shapes.Path{Data=Geometry.Parse("M18,7 A8,8 0 1 0 19,15 M18,2 V8 H12"),Stroke=Brush("#76DCCB"),StrokeThickness=2.3,StrokeStartLineCap=PenLineCap.Round,StrokeEndLineCap=PenLineCap.Round,Width=21,Height=21,Stretch=Stretch.Uniform};refresh.Width=46;refresh.Height=46;refresh.Padding=new Thickness(10);refresh.BorderBrush=Brush("#76DCCB");refresh.Background=Checker();refresh.ToolTip="Refresh recorded sessions";refresh.Margin=new Thickness(8,0,0,0);tools.Children.Add(refresh);
  var brand=new StackPanel();brand.Children.Add(Text("YOUR PLAY / PULSE",30,"#F3F2ED",FontWeights.Black));brand.Children.Add(Text(report.Days[0].Date.ToString("dd MMM")+" — "+DateTime.Today.ToString("dd MMM yyyy")+"  ·  A closer look at your library",12,"#ADAAB3"));heading.Children.Add(brand);content.Children.Add(heading);
  string trend=report.PreviousSeconds>0?$"{(report.Seconds/report.PreviousSeconds-1)*100:+0;-0;0}% vs previous {activityDays} days":report.Seconds>0?"Your first recorded time in this comparison":"Ready for your next adventure";
  var metrics=new UniformGrid{Columns=ActualWidth<1100?2:4,Margin=new Thickness(-6,0,-6,18)};
  void Metric(string label,string value,string detail,string color){var s=new StackPanel{Margin=new Thickness(17,14,17,14)};s.Children.Add(Text(label,12,"#B6B2BD",FontWeights.Bold));s.Children.Add(Text(value,34,color,FontWeights.Black));s.Children.Add(Text(detail,11,"#ADAAB3"));metrics.Children.Add(new Border{Background=Brush("#252528"),BorderBrush=Brush("#3C3C42"),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(15),Margin=new Thickness(6,0,6,10),Child=s});}
  Metric("TIME PLAYED",Hours(report.Seconds),trend,"#E1FF46");Metric("SESSIONS",report.Launches.ToString("00"),"Launches started in this period","#FF957F");Metric("YOUR ROTATION",report.GamesPlayed.ToString("00"),"Games with recorded playtime","#76DCCB");Metric("ACTIVE DAYS",report.ActiveDays.ToString("00")+" / "+activityDays,"Days you made time to play","#B1A0E5");content.Children.Add(metrics);
  var rhythm=new StackPanel();rhythm.Children.Add(new PlayChart(report.Days,false){Height=194});var note=Text("Hover a bar for the day’s recorded time. Older sessions use their start date.",11,"#A7A3AF");note.Margin=new Thickness(0,12,0,0);rhythm.Children.Add(note);
  var focus=new StackPanel();focus.Children.Add(new FocusChart(report.FocusSeconds,report.FocusMeasuredSeconds){Height=204,Margin=new Thickness(0,10,0,22)});double coverage=report.AllSeconds>0?report.FocusMeasuredSeconds/report.AllSeconds:0;focus.Children.Add(Text(report.FocusMeasuredSeconds>0?$"{Hours(report.FocusSeconds)} in focus  ·  {Hours(report.FocusMeasuredSeconds-report.FocusSeconds)} background":"Focus data appears after a tracked session.",12));focus.Children.Add(Text($"Measured coverage: {coverage:P0} of all recorded time",11,"#A7A3AF"));
  Pair(StatsPanel("THE DAILY RHYTHM","Recorded playtime · "+activityDays+" days",rhythm),StatsPanel("IN THE ZONE","All-time foreground share · measured sessions only",focus),2);
  var heat=new StackPanel();heat.Children.Add(new PlayChart(ninety.Days,true){Height=154});var peak=ninety.Days.OrderByDescending(d=>d.Seconds).First();heat.Children.Add(Text(ninety.Seconds>0?$"Busiest day: {peak.Date:dd MMM}  /  {Hours(peak.Seconds)}":"Your next session starts the pattern.",13,"#CEC9D5"));heat.Children.Add(Text("Each square is one day. Brighter means more playtime.",11,"#A7A3AF"));
  var sessionsPanel=new StackPanel();sessionsPanel.Children.Add(Text(Hours(report.AverageSession),36,"#FF957F",FontWeights.Black));sessionsPanel.Children.Add(Text("AVERAGE SESSION",11,"#B6B2BD",FontWeights.Bold));sessionsPanel.Children.Add(Text("Longest  /  "+Hours(report.LongestSession),18,"#EAE6EF"));sessionsPanel.Children.Add(Text("Whole recorded durations of sessions started in the selected period.",11,"#A7A3AF"));sessionsPanel.Children.Add(Text($"{report.Interrupted} interrupted  ·  {report.Unmeasured} without duration",12,"#B6B2BD"));
  Pair(StatsPanel("90 DAYS, ONE PATTERN","Your calendar of play · always the last 90 days",heat),StatsPanel("SESSION NOTES","The shape of your time",sessionsPanel),2);
  var ranking=new StackPanel();double total=Math.Max(1,report.Seconds);int rank=0;foreach(var entry in report.Ranking.Take(6)){int index=rank++;var row=new Grid{Margin=new Thickness(0,0,0,16)};row.ColumnDefinitions.Add(new(){Width=new GridLength(44)});row.ColumnDefinitions.Add(new(){Width=new GridLength(1,GridUnitType.Star)});row.ColumnDefinitions.Add(new(){Width=new GridLength(105)});row.Children.Add(new Border{Width=34,Height=43,CornerRadius=new CornerRadius(5),Background=new ImageBrush(LoadImage(entry.Game.CoverPath,68)??LoadImage(CachedIcon(entry.Game),68)??brandIcon){Stretch=Stretch.UniformToFill}});var middle=new StackPanel{Margin=new Thickness(10,0,14,0),VerticalAlignment=VerticalAlignment.Center};var name=Text(entry.Game.Name,19,"#F0EDE5",FontWeights.Black);name.TextWrapping=TextWrapping.NoWrap;name.TextTrimming=TextTrimming.CharacterEllipsis;middle.Children.Add(name);var bar=new Grid{Height=6,Margin=new Thickness(0,7,0,0),Background=Brush("#37373C")};bar.ColumnDefinitions.Add(new(){Width=new GridLength(entry.Seconds/total,GridUnitType.Star)});bar.ColumnDefinitions.Add(new(){Width=new GridLength(Math.Max(.001,1-entry.Seconds/total),GridUnitType.Star)});bar.Children.Add(new Border{Background=Brush(ChartColors[index]),CornerRadius=new CornerRadius(3)});middle.Children.Add(bar);Grid.SetColumn(middle,1);row.Children.Add(middle);var time=Text(Hours(entry.Seconds)+"  /  "+(entry.Seconds/total).ToString("P0"),13,ChartColors[index]);time.VerticalAlignment=VerticalAlignment.Center;time.HorizontalAlignment=HorizontalAlignment.Right;Grid.SetColumn(time,2);row.Children.Add(time);ranking.Children.Add(row);}if(rank==0)ranking.Children.Add(Text("Your most-played games will appear here.",14,"#AAA8AF"));
  var gamesPanel=StatsPanel("THE GAMES THAT GOT YOUR TIME","Share of recorded playtime in this period",ranking);gamesPanel.Margin=new Thickness(0,0,0,18);content.Children.Add(gamesPanel);
  var recent=new StackPanel();foreach(var s in report.Recent){var game=library.Games.First(g=>g.Id==s.GameId);var row=new Grid{Margin=new Thickness(0,0,0,15)};row.ColumnDefinitions.Add(new(){Width=new GridLength(1,GridUnitType.Star)});row.ColumnDefinitions.Add(new(){Width=new GridLength(165)});row.ColumnDefinitions.Add(new(){Width=new GridLength(100)});row.ColumnDefinitions.Add(new(){Width=new GridLength(120)});var name=Text(game.Name,17,"#F0EDE5",FontWeights.Black);name.TextWrapping=TextWrapping.NoWrap;name.TextTrimming=TextTrimming.CharacterEllipsis;row.Children.Add(name);var date=Text(s.Started.LocalDateTime.ToString("dd MMM  ·  HH:mm"),12,"#ABA7B3");Grid.SetColumn(date,1);row.Children.Add(date);var time=Text(Hours(s.Seconds),13,"#F2D17E");Grid.SetColumn(time,2);row.Children.Add(time);var state=Text(s.Status,12,s.Status=="Completed"?"#76DCCB":"#FF957F");Grid.SetColumn(state,3);row.Children.Add(state);recent.Children.Add(row);}if(report.Recent.Length==0)recent.Children.Add(Text("No launches in this period. Your history stays here when you play.",14));recent.Children.Add(Btn("Export history CSV",Export));content.Children.Add(StatsPanel("THE SESSION LOG","Latest launches in this period · game / start / duration / status",recent));
  status.Text="Recorded process time includes pauses. Foreground time does not measure attention. All history stays on this PC.";
 }
 void Pair(UIElement left,UIElement right,double ratio){var grid=new Grid{Margin=new Thickness(0,0,0,18)};grid.ColumnDefinitions.Add(new(){Width=new GridLength(ratio,GridUnitType.Star)});grid.ColumnDefinitions.Add(new(){Width=new GridLength(18)});grid.ColumnDefinitions.Add(new(){Width=new GridLength(1,GridUnitType.Star)});grid.Children.Add(left);Grid.SetColumn(right,2);grid.Children.Add(right);content.Children.Add(grid);}
}
