using System;
using System.Linq;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using System.Text.Json;
using System.Windows;
using System.Windows.Controls;
using Playdeck.Core;
namespace Playdeck;
public sealed partial class MainWindow {
 Func<string,Task<System.Collections.Generic.List<SteamMatch>>>? matchSearchProbe;Func<Game,Task>? matchFetchProbe;
 void ChooseSteamMatch(Game game){var body=new StackPanel();body.Children.Add(Text("Find the right game",26));var description=Text("Search Steam, then choose the title you want. Only your selection updates this card.",14,"#B7B7B7");description.Margin=new Thickness(0,12,0,18);body.Children.Add(description);var query=new TextBox{Text=game.Name,Margin=new Thickness(0,0,0,14)};body.Children.Add(query);var results=new StackPanel();var info=Text("",13,"#CACACA");var dialog=Dialog("Choose Steam match",body,620);using var stop=CancellationTokenSource.CreateLinkedTokenSource(lifetime.Token);dialog.Closed+=(_,_)=>stop.Cancel();bool busy=false;async Task Search(){if(busy)return;busy=true;results.Children.Clear();info.Text="Searching Steam…";try{var matches=await (matchSearchProbe?.Invoke(query.Text)??metadata.Search(query.Text,root,stop.Token));if(stop.IsCancellationRequested)return;info.Text=matches.Count==0?"No matches. Try a shorter or different title.":"Choose a match to update the title and cover.";foreach(var match in matches){var button=Btn(match.Name,async()=>{if(busy)return;busy=true;info.Text="Fetching selected artwork…";results.IsEnabled=false;try{var candidate=JsonSerializer.Deserialize<Game>(JsonSerializer.Serialize(game,Store.Json),Store.Json)!;candidate.SteamId=match.Id;candidate.MetadataAttempted=false;candidate.CoverPath="";await (matchFetchProbe?.Invoke(candidate)??metadata.Fetch(candidate,root,stop.Token));if(stop.IsCancellationRequested)return;if(candidate.MetadataStatus.StartsWith("Steam")){if(game.SteamId!=candidate.SteamId&&game.VersionInfo.ReleaseAppId==0&&game.VersionInfo.GitHubRepository.Length==0){ReleaseVersions.Clear(game.VersionInfo);game.VersionInfo.ConfirmedReleaseSource="";}game.SteamId=candidate.SteamId;game.Name=candidate.Name;game.ReleaseDate=candidate.ReleaseDate;game.MetadataAttempted=true;game.MetadataStatus=candidate.MetadataStatus;if(File.Exists(candidate.CoverPath))game.CoverPath=candidate.CoverPath;Save();dialog.Close();Render();}else info.Text="This match could not be loaded. Try another result.";}finally{busy=false;results.IsEnabled=true;}});button.Content=Text(match.Name,18);button.HorizontalContentAlignment=HorizontalAlignment.Left;button.Margin=new Thickness(0,0,0,10);results.Children.Add(button);}}catch(OperationCanceledException){}catch(Exception ex){info.Text="Steam search unavailable: "+ex.Message;}finally{busy=false;}}
 var searchButton=Btn("Search Steam",async()=>await Search(),true);body.Children.Add(searchButton);body.Children.Add(info);body.Children.Add(new ScrollViewer{Content=results,MaxHeight=330,Margin=new Thickness(0,18,0,10)});query.KeyDown+=async(_,e)=>{if(e.Key==System.Windows.Input.Key.Enter){e.Handled=true;await Search();}};body.Children.Add(Btn("Cancel",()=>dialog.Close()));if(dialogProbe==null)dialog.ContentRendered+=async(_,_)=>await Search();dialog.ShowDialog();}
 void EmptyTrash(){var removed=library.Games.Where(g=>g.Removed).ToArray();if(removed.Length==0)return;var body=new StackPanel();body.Children.Add(Text("Empty Trash?",26));body.Children.Add(Text($"Permanently remove {removed.Length} cards from Playdeck. They cannot be restored from Trash afterward. Installed game files are untouched.",14));var dialog=Dialog("Empty Trash",body,510);var actions=new WrapPanel{Margin=new Thickness(0,22,0,0)};actions.Children.Add(Btn("Empty Trash",()=>{library.Games.RemoveAll(g=>g.Removed);Save();dialog.Close();Render();},true));actions.Children.Add(Btn("Cancel",()=>dialog.Close()));body.Children.Add(actions);dialog.ShowDialog();}
}
