using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using Playdeck.Core;
namespace Playdeck;
public sealed partial class MainWindow {
 bool selectionMode; readonly HashSet<string> selected=[];
 void TrashGames(IEnumerable<Game> games){foreach(var game in games.ToArray())LibraryActions.Remove(library,game);selected.Clear();Save();Render();status.Text="Moved to Trash · Recover within 7 days. Your game files are untouched.";}
 StackPanel Section(string title,string description){var body=new StackPanel();body.Children.Add(Text(title,24,"#F0EDE5",FontWeights.Bold));if(description.Length>0){var t=Text(description,14,"#B8B4B8");t.Margin=new Thickness(0,8,0,16);body.Children.Add(t);}content.Children.Add(new Border{Background=Brush("#242427"),CornerRadius=new CornerRadius(16),Padding=new Thickness(24),Margin=new Thickness(0,0,0,18),Child=body});return body;}
 void Trash(){var body=Section("A second chance","Cards stay here for 7 days. Restoring keeps artwork, pins and activity. Game files are never deleted.");var games=library.Games.Where(g=>g.Removed).ToArray();if(games.Length==0)body.Children.Add(Text("Your trash is empty.",18));else body.Children.Add(Btn("Restore all",()=>{foreach(var g in games)LibraryActions.Restore(library,g);Save();Render();}));if(games.Length>0)body.Children.Add(Btn("Empty Trash…",EmptyTrash));foreach(var g in games){var row=new DockPanel{Margin=new Thickness(0,16,0,0)};var restore=Btn("Restore",()=>{LibraryActions.Restore(library,g);Save();Render();});DockPanel.SetDock(restore,Dock.Right);row.Children.Add(restore);var image=new Image{Source=LoadImage(g.CoverPath,80)??city,Width=42,Height=54,Margin=new Thickness(0,0,16,0)};DockPanel.SetDock(image,Dock.Left);row.Children.Add(image);var label=Text(g.Name+"\n"+Math.Max(0,7-(int)(DateTimeOffset.UtcNow-(g.TrashedAt??DateTimeOffset.UtcNow)).TotalDays)+" days left",14);label.VerticalAlignment=VerticalAlignment.Center;row.Children.Add(label);body.Children.Add(row);}status.Text="Trash · recoverable for 7 days";}
 void Settings(){
 IntegrationSettings();
 var profile=Section("PLAYER PROFILE","Customize the player card in the top-left corner.");profile.Children.Add(Btn("Edit profile",EditProfile));
 var art=Section("Artwork on autopilot","Titles and Steam IDs are used for online matching. Results are cached locally; unmatched games show their icon on your default cover. Paste your own image in the card editor.");var online=new CheckBox{Content="Fetch titles, release dates and artwork",IsChecked=library.Online};online.Click+=(_,_)=>{library.Online=online.IsChecked==true;Save();if(library.Online)_=Enrich();};art.Children.Add(online);
 var history=Section("Keep the story","Archived games retain cached icons, covers and activity even when their installation disappears. The tracking helper runs only during games launched through Playdeck.");history.Children.Add(Btn("Export sessions CSV",Export));
 var reset=Section("Make a fresh start","Move every card, including archived games, to Trash and start again. Restore cards within 7 days. Installed games are never touched.");reset.Children.Add(Btn("Reset library…",()=>{var body=new StackPanel();body.Children.Add(Text("Move all cards to Trash?",24));body.Children.Add(Text("This clears the current library. Your installed games are untouched. You can restore cards from Trash for 7 days.",14));var dialog=Dialog("Start fresh",body,510);var buttons=new WrapPanel{Margin=new Thickness(0,24,0,0)};buttons.Children.Add(Btn("Move all to Trash",()=>{LibraryActions.StartFresh(library);selected.Clear();Save();dialog.Close();Render();},true));buttons.Children.Add(Btn("Cancel",()=>dialog.Close()));body.Children.Add(buttons);dialog.ShowDialog();}));status.Text="Local data · "+root;
 }
 void Activity(){
 if(!demo)sessions=Store.Sessions(root);var ids=library.Games.Where(g=>!g.Removed).Select(g=>g.Id).ToHashSet();var active=sessions.Where(s=>ids.Contains(s.GameId)).ToArray();
 var overview=Section("Your play story","A little time away. A library full of adventures.");var metrics=new Grid();for(int i=0;i<3;i++)metrics.ColumnDefinitions.Add(new(){Width=new GridLength(1,GridUnitType.Star)});var values=new[]{(Hours(active.Sum(s=>s.Seconds)),"TOTAL PLAYTIME"),(active.Length.ToString(),"LAUNCHES"),(active.Select(s=>s.GameId).Distinct().Count().ToString(),"GAMES PLAYED")};for(int i=0;i<3;i++){var stack=new StackPanel{Margin=new Thickness(0,12,16,8)};stack.Children.Add(Text(values[i].Item1,36,"#FF957F",FontWeights.Bold));stack.Children.Add(Text(values[i].Item2,12,"#C1BBC0"));Grid.SetColumn(stack,i);metrics.Children.Add(stack);}overview.Children.Add(metrics);
 var daily=Section("The last 14 days","Recorded time per local day. Older sessions use their start date.");var chart=new Grid{Height=170};var totals=Enumerable.Range(0,14).Select(i=>active.Sum(s=>SessionAccounting.OnDay(s,DateTime.Today.AddDays(i-13)))).ToArray();var max=Math.Max(3600,totals.Max());for(int i=0;i<14;i++){chart.ColumnDefinitions.Add(new(){Width=new GridLength(1,GridUnitType.Star)});var col=new DockPanel{Margin=new Thickness(5,0,5,0)};var label=Text(DateTime.Today.AddDays(i-13).ToString("dd"),11,"#BBB5BB");label.HorizontalAlignment=HorizontalAlignment.Center;DockPanel.SetDock(label,Dock.Bottom);col.Children.Add(label);col.Children.Add(new Border{Height=Math.Max(3,140*totals[i]/max),CornerRadius=new CornerRadius(5,5,0,0),VerticalAlignment=VerticalAlignment.Bottom,Background=Brush(i==13?"#FF765E":"#7673AD"),ToolTip=Hours(totals[i])});Grid.SetColumn(col,i);chart.Children.Add(col);}daily.Children.Add(chart);
 var detail=Section("A closer look", "Process time includes pauses. Focus time means the game was the foreground window.");
 var played=active.Where(s=>s.Seconds>0).ToArray();double week=Enumerable.Range(0,7).Sum(i=>active.Sum(s=>SessionAccounting.OnDay(s,DateTime.Today.AddDays(-i))));double previous=Enumerable.Range(7,7).Sum(i=>active.Sum(s=>SessionAccounting.OnDay(s,DateTime.Today.AddDays(-i))));
 detail.Children.Add(Text($"This week  {Hours(week)}     /     Previous week  {Hours(previous)}",18));
 detail.Children.Add(Text($"Average session  {Hours(played.Length==0?0:played.Average(s=>s.Seconds))}     /     Longest  {Hours(played.Length==0?0:played.Max(s=>s.Seconds))}",14));
 var focused=active.Where(s=>s.HasFocusData).ToArray();detail.Children.Add(Text(focused.Length==0?"Focus time will appear after your next tracked game.":$"In focus  {Hours(focused.Sum(s=>s.ForegroundSeconds))}     /     Background  {Hours(focused.Sum(s=>Math.Max(0,s.Seconds-s.ForegroundSeconds)))}",14));
 detail.Children.Add(Text($"{active.Count(s=>s.Status=="Interrupted")} interrupted  /  {active.Count(s=>s.Status is "Not detected" or "Launch only")} launches without duration",12,"#BBB5BB"));
 var ranking=Section("Time well spent","");var ranked=library.Games.Where(g=>!g.Removed).Select(g=>(g,seconds:History(g).Sum(s=>s.Seconds))).Where(x=>x.seconds>0).OrderByDescending(x=>x.seconds).Take(6).ToArray();foreach(var item in ranked){var row=new StackPanel{Margin=new Thickness(0,16,0,0)};row.Children.Add(Text(item.g.Name+"  ·  "+Hours(item.seconds)));var bar=new Grid{Margin=new Thickness(0,8,0,0),Height=6};double ratio=item.seconds/ranked[0].seconds;bar.ColumnDefinitions.Add(new(){Width=new GridLength(ratio,GridUnitType.Star)});bar.ColumnDefinitions.Add(new(){Width=new GridLength(Math.Max(.0001,1-ratio),GridUnitType.Star)});bar.Children.Add(new Border{Background=Brush("#FF957F"),CornerRadius=new CornerRadius(3)});row.Children.Add(bar);ranking.Children.Add(row);}
 var recent=Section("Recent sessions","");if(active.Length==0)recent.Children.Add(Text("Launch a game to begin your story."));foreach(var s in active.OrderByDescending(s=>s.Started).Take(12)){var row=new DockPanel{Margin=new Thickness(0,14,0,0)};var duration=Text(Hours(s.Seconds),14,"#FF957F");duration.Margin=new Thickness(20,0,0,0);DockPanel.SetDock(duration,Dock.Right);row.Children.Add(duration);row.Children.Add(Text(library.Games.First(g=>g.Id==s.GameId).Name+"  ·  "+s.Started.LocalDateTime.ToString("MMM dd, HH:mm")+"  ·  "+s.Status,14));recent.Children.Add(row);}status.Text="Paused time counts as playtime. Interrupted sessions retain their last recorded checkpoint.";
 }
}
