using System;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;
namespace Playdeck;
public sealed partial class MainWindow {
 Button? profileButton;readonly ScrollViewer libraryScroll=new();
 static System.Windows.Media.Brush Checker()=> (System.Windows.Media.Brush)Application.Current.FindResource("Checker");
 void BuildShell(){
 WindowStyle=WindowStyle.None;Icon=brandIcon;
 System.Windows.Shell.WindowChrome.SetWindowChrome(this,new System.Windows.Shell.WindowChrome{CaptionHeight=0,ResizeBorderThickness=new Thickness(6),GlassFrameThickness=new Thickness(0),UseAeroCaptionButtons=false});
 var shell=new DockPanel{Background=(System.Windows.Media.Brush)Application.Current.FindResource("Backdrop")};Content=shell;
 var header=new Border{Background=Brush("#050505"),Padding=new Thickness(22,16,16,16),BorderBrush=Brush("#333333"),BorderThickness=new Thickness(0,0,0,2)};DockPanel.SetDock(header,Dock.Top);shell.Children.Add(header);
 var row=new Grid();row.RowDefinitions.Add(new(){Height=new GridLength(52)});row.RowDefinitions.Add(new(){Height=GridLength.Auto});header.Child=row;foreach(var w in new[]{new GridLength(56),new GridLength(195),new GridLength(1,GridUnitType.Star),new GridLength(140)})row.ColumnDefinitions.Add(new(){Width=w});
 var back=Btn("↶",()=>{view="Library";search.Text="";Render();});back.Content=new System.Windows.Shapes.Path{Data=Geometry.Parse("M28,7 L18,7 L18,2 L5,12 L18,22 L18,17 L27,17 C35,17 35,29 25,29 L18,29 L18,35 L27,35 C45,35 45,7 28,7 Z"),Fill=Brush("#FF492E"),Width=24,Height=24,Stretch=Stretch.Uniform};back.FontSize=31;back.Foreground=Brush("#FF492E");back.BorderBrush=Brush("#FF492E");back.BorderThickness=new Thickness(3);back.Background=Checker();back.MinHeight=46;back.Margin=new Thickness(0,0,8,0);back.Padding=new Thickness(6);back.Height=46;back.ToolTip="Back to library";row.Children.Add(back);
 profileButton=Btn("",EditProfile);profileButton.Padding=new Thickness(4,3,9,3);profileButton.BorderThickness=new Thickness(2);profileButton.BorderBrush=Brush("#484848");profileButton.Background=new LinearGradientBrush((Color)ColorConverter.ConvertFromString("#393939"),(Color)ColorConverter.ConvertFromString("#202020"),90);profileButton.Height=52;profileButton.Margin=new Thickness(6,0,16,0);profileButton.ToolTip="Customize your profile";Grid.SetColumn(profileButton,1);row.Children.Add(profileButton);UpdateProfile();
 var rail=new Border{Background=Checker(),BorderBrush=Brush("#464646"),BorderThickness=new Thickness(4),CornerRadius=new CornerRadius(28),Height=52,VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(0,0,12,0)};Grid.SetColumn(rail,2);row.Children.Add(rail);var nav=new Grid();rail.Child=nav;int index=0;foreach(var label in new[]{"Library","Pinned","Activity","Archived","Trash","Settings"}){nav.ColumnDefinitions.Add(new(){Width=new GridLength(1,GridUnitType.Star)});string route=label=="Settings"?"Folders & settings":label;var b=Btn(label,()=>{view=route;selectionMode=false;selected.Clear();Render();});b.Style=(Style)FindResource("NavButton");b.Margin=new Thickness(-1,-3,-1,-3);b.Padding=new Thickness(4,0,4,0);b.FontSize=21;b.ToolTip=label;Grid.SetColumn(b,index++);nav.Children.Add(b);navigation[route]=b;}
 var controls=new StackPanel{Orientation=Orientation.Horizontal,VerticalAlignment=VerticalAlignment.Center};Grid.SetColumn(controls,3);row.Children.Add(controls);foreach(var item in new[]{("−","Minimize",(Action)(()=>WindowState=WindowState.Minimized)),("□","Maximize",()=>WindowState=WindowState==WindowState.Maximized?WindowState.Normal:WindowState.Maximized),("×","Close",()=>Close())}){var b=Btn(item.Item1,item.Item3);b.Width=42;b.Height=42;b.Padding=new Thickness(0);b.Margin=new Thickness(3,0,0,0);b.FontSize=20;b.Foreground=Brush(item.Item2=="Close"?"#FF604A":item.Item2=="Maximize"?"#76DCCB":"#F5D260");b.BorderBrush=b.Foreground;b.BorderThickness=new Thickness(2);b.ToolTip=item.Item2;b.Content=new System.Windows.Shapes.Path{Data=Geometry.Parse(item.Item2=="Close"?"M1,1 L11,11 M11,1 L1,11":item.Item2=="Maximize"?"M1,1 H11 V11 H1 Z":"M1,6 H11"),Stroke=b.Foreground,StrokeThickness=2,Width=12,Height=12,Stretch=Stretch.Uniform,HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Center};controls.Children.Add(b);}
 bool? narrowBefore=null;void FitHeader(){bool narrow=ActualWidth>0&&ActualWidth<1120;if(narrowBefore==narrow)return;narrowBefore=narrow;Grid.SetRow(rail,narrow?1:0);Grid.SetColumn(rail,narrow?0:2);Grid.SetColumnSpan(rail,narrow?4:1);rail.Margin=narrow?new Thickness(0,16,0,0):new Thickness(0,0,14,0);}
 SizeChanged+=(_,_)=>FitHeader();Loaded+=(_,_)=>FitHeader();
 header.MouseLeftButtonDown+=(_,e)=>{if(!InsideButton(e.OriginalSource as DependencyObject)){if(e.ClickCount==2)WindowState=WindowState==WindowState.Maximized?WindowState.Normal:WindowState.Maximized;else DragMove();}};
 var main=new DockPanel{Margin=new Thickness(26,18,26,10)};shell.Children.Add(main);status.FontSize=11;status.Foreground=Brush("#B4B4B4");status.Margin=new Thickness(0,12,0,0);DockPanel.SetDock(status,Dock.Bottom);main.Children.Add(status);libraryScroll.Content=content;libraryScroll.Padding=new Thickness(0,0,10,0);main.Children.Add(libraryScroll);libraryScroll.ScrollChanged+=(_,e)=>{var panel=content.Children.OfType<CardPanel>().FirstOrDefault();if(panel!=null){double top=content.Children[0].DesiredSize.Height;panel.SetViewport(Math.Max(0,libraryScroll.VerticalOffset-top),libraryScroll.ViewportHeight);}};
 AllowDrop=true;DragOver+=(_,e)=>{if(e.Data.GetDataPresent(DataFormats.FileDrop)){e.Effects=DragDropEffects.Copy;e.Handled=true;}};Drop+=(_,e)=>{if(e.Data.GetData(DataFormats.FileDrop) is string[] files){QueueImports(files);e.Handled=true;}};
 }
 void UpdateProfile(){if(profileButton==null)return;var badge=new Grid{Width=150};badge.ColumnDefinitions.Add(new(){Width=new GridLength(44)});badge.ColumnDefinitions.Add(new(){Width=new GridLength(1,GridUnitType.Star)});var avatar=new Border{Width=42,Height=42,CornerRadius=new CornerRadius(21),BorderThickness=new Thickness(2),BorderBrush=Brush("#090909"),Background=new ImageBrush(LoadImage(library.AvatarPath,96)??brandIcon){Stretch=Stretch.UniformToFill}};badge.Children.Add(avatar);var name=new StackPanel{VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(8,0,0,0)};Grid.SetColumn(name,1);badge.Children.Add(name);var title=Text(library.UserName,20,"#F5F5F5",FontWeights.Black);title.TextWrapping=TextWrapping.NoWrap;title.TextTrimming=TextTrimming.CharacterEllipsis;name.Children.Add(title);name.Children.Add(Text("MY PROFILE",9,"#ADADAD",FontWeights.Bold));profileButton.Content=badge;}
 void AddMenu()=>AddGames();
}
