using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;
using Playdeck.Core;
namespace Playdeck;
public sealed partial class MainWindow {
 void SmokeV6(List<string> checks){
 void Check(string name,bool ok){if(!ok)throw new InvalidOperationException(name);checks.Add("PASS "+name);}
 var p=new CardPanel{CardWidth=100,Items=Enumerable.Range(0,100).Select(i=>new Game()).ToArray(),HeightFactory=_=>100,Factory=(_,_)=>new Border()};
 p.SetViewport(0,200);p.Measure(new Size(340,double.PositiveInfinity));var retained=p.Children[6];p.SetViewport(236,200);p.Measure(new Size(340,double.PositiveInfinity));Check("Scrolling preserves overlapping card instances",p.Children.Contains(retained));Check("Virtualization keeps realized cards bounded",p.Children.Count<25);
 int created=p.CreatedCards;p.SetViewport(0,200);p.Measure(new Size(340,double.PositiveInfinity));Check("Returning to recently visited rows reuses controls",p.CreatedCards==created);
 for(int i=0;i<40;i++){p.SetViewport(i*118,200);p.Measure(new Size(340,double.PositiveInfinity));}Check("Card control cache stays bounded",p.CachedCards<=72);
 view="Activity";activityDays=7;Render();UpdateLayout();Check("Activity has interactive time ranges and charts",content.Children.Count>=6);Capture(System.IO.Path.ChangeExtension(capture!,"pulse-week.png"));activityDays=90;Render();UpdateLayout();Capture(System.IO.Path.ChangeExtension(capture!,"pulse-quarter.png"));activityDays=30;libraryScroll.ScrollToVerticalOffset(640);UpdateLayout();Capture(System.IO.Path.ChangeExtension(capture!,"pulse-details.png"));libraryScroll.ScrollToTop();
 var versionGame=new Game{Name="Local game · demonstration",SteamId=367520,VersionInfo=new(){Mode="Manual",ManualVersion="1.9",ManualLatest="1.10"}};dialogProbe=window=>{var body=(StackPanel)((ScrollViewer)window.Content).Content;body.Children.OfType<WrapPanel>().Last().Children.OfType<Button>().Single(b=>(string)b.Content=="Save locally").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));};AdvancedVersionDialog(versionGame);dialogProbe=null;Check("Manual version editor saves comparable evidence without network",versionGame.VersionInfo.Installed=="1.9"&&versionGame.VersionInfo.NeedsUpdate);dialogProbe=window=>{CaptureWindow(window,System.IO.Path.ChangeExtension(capture!,"version.png"));window.Close();};AdvancedVersionDialog(versionGame);dialogProbe=null;
 versionGame.VersionInfo.ManualLatest="";versionGame.VersionInfo.LatestVersion="1.10";versionGame.VersionInfo.ReleaseSourceKey="steam-news:367520";versionGame.VersionInfo.ConfirmedReleaseSource="steam-news:367520";versionGame.VersionInfo.ReleaseTitle="Patch 1.10 is live";versionGame.VersionInfo.ReleasePublishedAt=DateTimeOffset.UtcNow.AddDays(-2);versionGame.VersionInfo.ReleaseCheckedAt=DateTimeOffset.UtcNow;versionGame.VersionInfo.NextReleaseCheckAt=DateTimeOffset.UtcNow.AddDays(1);versionGame.VersionInfo.Status="Newer release found";
 dialogProbe=window=>{var body=(StackPanel)((ScrollViewer)window.Content).Content;var fileBody=(StackPanel)body.Children.OfType<Expander>().Single().Content;Check("Guided version review exposes evidence and confirmation actions",fileBody.Children.OfType<ListBox>().Any()&&fileBody.Children.OfType<WrapPanel>().Single().Children.OfType<Button>().Any(b=>(string)b.Content=="Use selected"));Check("Local version review shows installed and published release side by side",body.Children.OfType<Grid>().Single().Children.Count==2&&body.Children.OfType<WrapPanel>().Single().Children.OfType<Button>().Any(b=>(string)b.Content=="Save & compare"));var auto=body.Children.OfType<CheckBox>().Single(c=>((string)c.Content).StartsWith("Check daily"));auto.IsChecked=true;auto.RaiseEvent(new RoutedEventArgs(System.Windows.Controls.Primitives.ButtonBase.ClickEvent));Check("Daily release preference persists without a separate save",versionGame.VersionInfo.AutoCheck);CaptureWindow(window,System.IO.Path.ChangeExtension(capture!,"version-guide.png"));window.Close();};VersionDialog(versionGame);dialogProbe=null;
 for(int i=0;i<Math.Min(8,library.Games.Count);i++)library.Games[i].CoverPath=System.IO.Path.Combine(root,"demo-art",i+".jpg");var demoVersions=library.Games.Take(3).ToArray();for(int i=0;i<demoVersions.Length;i++){demoVersions[i].VersionInfo=new(){ReleasePublishedAt=DateTimeOffset.UtcNow.AddDays(-i*14-1),ReleaseTitle="Published update · demo",Installed="1.2."+i,LocalAvailable=true,CheckedAt=DateTimeOffset.UtcNow,RemoteCheckedAt=DateTimeOffset.UtcNow,MatchesLatest=i==0,NeedsUpdate=i==1};}view="Library";Render();UpdateLayout();Capture(System.IO.Path.ChangeExtension(capture!,"version-banners.png"));var versionSurface=((Grid)content.Children.OfType<CardPanel>().Single().Children.OfType<Border>().First().Child).Children.OfType<GameSurface>().Single();var versionPeer=System.Windows.Automation.Peers.UIElementAutomationPeer.CreatePeerForElement(versionSurface);Check("Version chips retain compact accessible hit targets",versionPeer!=null&&versionPeer.GetBoundingRectangle().Width<=112*System.Windows.Media.VisualTreeHelper.GetDpi(versionSurface).DpiScaleX&&versionPeer.GetBoundingRectangle().Height>0);
 dialogProbe=window=>{var body=(StackPanel)((ScrollViewer)window.Content).Content;Check("Update date is primary and version controls are secondary",body.Children.OfType<TextBlock>().Any(x=>x.Text=="LAST PUBLISHED UPDATE")&&body.Children.OfType<Expander>().Single().Header.ToString()!.Contains("Optional"));CaptureWindow(window,System.IO.Path.ChangeExtension(capture!,"update-date.png"));window.Close();};UpdateDialog(versionGame);dialogProbe=null;
 var modeBefore=library.CardInfoMode;library.CardInfoMode="Off";view="Library";Render();UpdateLayout();var offSurface=((Grid)content.Children.OfType<CardPanel>().Single().Children.OfType<Border>().First().Child).Children.OfType<GameSurface>().Single();Check("Hidden update banner has no click interception",!offSurface.IsVersionHit(new Point(20,20)));library.CardInfoMode=modeBefore;
 sort.SelectedIndex=7;Render();Check("Published update date sort renders without changing pin mode",content.Children.OfType<CardPanel>().Any());sort.SelectedIndex=0;
 var toolFixture=new Game{Name="Tool fixture",LaunchPath=Environment.ProcessPath!};dialogProbe=window=>{var body=(StackPanel)((ScrollViewer)window.Content).Content;body.Children.OfType<CheckBox>().Single(c=>((string)c.Content).StartsWith("Mark as tool")).IsChecked=true;body.Children.OfType<WrapPanel>().SelectMany(p=>p.Children.OfType<Button>()).Single(b=>(string)b.Content=="Save changes").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));};Edit(toolFixture);dialogProbe=null;Check("Card settings save tool launch mode",toolFixture.IsTool);int openedTools=0;int historyBefore=sessions.Count;toolStartProbe=_=>openedTools++;Launch(toolFixture).GetAwaiter().GetResult();toolStartProbe=null;Check("Tool card launch leaves UI open and history unchanged",openedTools==1&&IsVisible&&sessions.Count==historyBefore);
 var opaque=Enumerable.Repeat((byte)255,8*8*4).ToArray();var square=System.Windows.Media.Imaging.BitmapSource.Create(8,8,96,96,System.Windows.Media.PixelFormats.Bgra32,null,opaque,32);Check("Opaque square icons receive rounded corners",IconShape.IsOpaqueSquare(square));opaque[3]=0;var shaped=System.Windows.Media.Imaging.BitmapSource.Create(8,8,96,96,System.Windows.Media.PixelFormats.Bgra32,null,opaque,32);var wide=System.Windows.Media.Imaging.BitmapSource.Create(8,4,96,96,System.Windows.Media.PixelFormats.Bgra32,null,opaque,32);Check("Shaped and non-square icons keep their outlines",!IconShape.IsOpaqueSquare(shaped)&&!IconShape.IsOpaqueSquare(wide));
 var g=new Game{IconPath=Environment.ProcessPath!};CacheIcon(g);var a=LoadImage(CachedIcon(g),64);Check("Decoded images are reused and frozen",a!=null&&a.IsFrozen&&ReferenceEquals(a,LoadImage(CachedIcon(g),64)));
 for(int i=1;i<=170;i++)LoadImage(CachedIcon(g),i);Check("Decoded image cache has an enforced memory and entry bound",imageCache.Count<=160&&imageBytes<=48*1024*1024);
 }
}
