using System;
using System.Diagnostics;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using Playdeck.Core;
namespace Playdeck;
public sealed partial class MainWindow {
 void OpenGameUpdate(Game game){if(library.CardInfoMode=="Version")VersionDialog(game);else UpdateDialog(game);}
 void UpdateSettings(){
  var panel=Section("UPDATE RADAR","See the last published update on each card. Dates come from publisher posts, not from changes to your local files.");
  panel.Children.Add(Text("CARD BANNER",12,"#76DDD3"));var mode=new ComboBox{ItemsSource=new[]{"Update date","Version","Off"},SelectedItem=library.CardInfoMode,Margin=new Thickness(0,8,0,16),MaxWidth=320,HorizontalAlignment=HorizontalAlignment.Left};mode.SelectionChanged+=(_,_)=>{library.CardInfoMode=(string)mode.SelectedItem;Save();};panel.Children.Add(mode);
  var daily=new CheckBox{Content="Refresh update dates daily while Playdeck is open",IsChecked=library.CheckUpdateDates,Margin=new Thickness(0,0,0,16)};daily.Click+=(_,_)=>{library.CheckUpdateDates=daily.IsChecked==true;Save();};panel.Children.Add(daily);panel.Children.Add(Btn("Browse update dates",()=>UpdateLibrary(),true));panel.Children.Add(Btn("Optional version comparisons",VersionHub));
  var tracking=Section("PLAYTIME TRACKING","Turn tracking off to launch directly and close Playdeck with no tracking helper. Existing history stays saved; new playtime will not be recorded.");var enabled=new CheckBox{Content="Record playtime for games I launch",IsChecked=library.TrackPlaytime};enabled.Click+=(_,_)=>{library.TrackPlaytime=enabled.IsChecked==true;Save();};tracking.Children.Add(enabled);
 }
 void UpdateLibrary(){var body=new StackPanel();body.Children.Add(Text("PUBLISHED UPDATES",27,"#76DDD3"));body.Children.Add(Text("Newest publisher update first. REL means original release date when no update was found.",13,"#BAB5C4"));var list=new ListBox{Height=340,Margin=new Thickness(0,18,0,12),DisplayMemberPath="Label"};body.Children.Add(list);var statusText=Text("",13,"#BAB5C4");body.Children.Add(statusText);var actions=new WrapPanel();body.Children.Add(actions);var dialog=Dialog("Update radar",body,750);using var stop=CancellationTokenSource.CreateLinkedTokenSource(lifetime.Token);dialog.Closed+=(_,_)=>stop.Cancel();
  void Refresh(){list.ItemsSource=library.Games.Where(g=>!g.Removed&&!g.Archived&&!g.IsTool).OrderByDescending(UpdateDates.SortDate).ThenBy(g=>g.Name).Select(g=>new UpdateRow(g,g.Name+"  /  "+UpdateDates.Label(g))).ToArray();}Refresh();list.SelectionChanged+=(_,_)=>{if(list.SelectedItem is UpdateRow row){list.SelectedItem=null;UpdateDialog(row.Game);Refresh();}};
  actions.Children.Add(Btn("Check dates",async()=>{actions.IsEnabled=false;list.IsEnabled=false;bool dirty=false;try{var games=library.Games.Where(g=>!g.Removed&&!g.Archived&&!g.IsTool).ToArray();int i=0;foreach(var game in games){statusText.Text=$"Checking {++i}/{games.Length} · {game.Name}";string key=VersionKey(game);var snapshot=JsonSerializer.Deserialize<Game>(JsonSerializer.Serialize(game,Store.Json),Store.Json)!;var result=await versions.CheckUpdates(snapshot,root,library.Online,stop.Token);if(stop.IsCancellationRequested)return;if(VersionKey(game)==key&&!game.Removed){game.VersionInfo=result;dirty=true;if(i%10==0){Save();dirty=false;}}}statusText.Text=$"{games.Count(g=>g.VersionInfo.ReleasePublishedAt.HasValue)}/{games.Length} games have a published update date. Cached at least 24 hours.";Refresh();Render();}catch(OperationCanceledException){}catch(Exception e){statusText.Text=e.Message;}finally{if(dirty)Save();actions.IsEnabled=true;list.IsEnabled=true;}},true));actions.Children.Add(Btn("Done",()=>dialog.Close()));dialog.ShowDialog();
 }
 sealed record UpdateRow(Game Game,string Label);
 void UpdateDialog(Game game){
  var body=new StackPanel();body.Children.Add(Text("LAST PUBLISHED UPDATE",25,"#76DDD3"));body.Children.Add(Text(game.Name,21));var date=Text("",36);date.Margin=new Thickness(0,22,0,10);body.Children.Add(date);var title=Text("",17);body.Children.Add(title);var info=Text("",13,"#BAB5C4");info.Margin=new Thickness(0,16,0,18);body.Children.Add(info);
  var actions=new WrapPanel();body.Children.Add(actions);var extra=new StackPanel();var hintToggle=new CheckBox{Content="Compare my confirmed build date · optional hint only",IsChecked=game.VersionInfo.CompareBuildDate,Margin=new Thickness(0,14,0,12)};extra.Children.Add(hintToggle);var buildDate=new TextBox{Text=game.VersionInfo.ConfirmedBuildDate.Length>0?game.VersionInfo.ConfirmedBuildDate:UpdateDates.BuildDate(game.VersionInfo.Installed)!=null?game.VersionInfo.Installed:"",Margin=new Thickness(0,0,0,12)};extra.Children.Add(buildDate);extra.Children.Add(Text("Enter a verified YYYY.MM.DD build label. Saving confirms this publisher feed matches your PC edition. A later post suggests reviewing updates; matching dates never prove you are current. File modification dates are not used.",12,"#BAB5C4"));
  var dialog=Dialog("Update · "+game.Name,body,700);using var stop=CancellationTokenSource.CreateLinkedTokenSource(lifetime.Token);dialog.Closed+=(_,_)=>stop.Cancel();bool busy=false;
  void Refresh(){var v=game.VersionInfo;date.Text=v.ReleasePublishedAt?.UtcDateTime.ToString("dd MMM yyyy")??game.ReleaseDate?.ToString("dd MMM yyyy")??"Date unknown";title.Text=v.ReleasePublishedAt.HasValue?v.ReleaseTitle:game.ReleaseDate.HasValue?"Original release date · update date not found":"No update post found in this source";info.Text=(UpdateDates.PossibleUpdate(v)?"A publisher update was posted after your build date. Review the notes.\n\n":"")+"This is a publisher date, not your installed update date.\n"+(v.ReleaseCheckedAt.HasValue?"Checked "+v.ReleaseCheckedAt.Value.LocalDateTime.ToString("dd MMM HH:mm"):"Not checked yet")+(v.NextReleaseCheckAt.HasValue?" · next check "+v.NextReleaseCheckAt.Value.LocalDateTime.ToString("dd MMM HH:mm"):"")+"\n"+v.ReleaseError;}
  async Task Check(){if(busy)return;busy=true;actions.IsEnabled=false;try{string key=VersionKey(game);var snapshot=JsonSerializer.Deserialize<Game>(JsonSerializer.Serialize(game,Store.Json),Store.Json)!;info.Text="Checking publisher updates…";var result=await versions.CheckUpdates(snapshot,root,library.Online,stop.Token);if(stop.IsCancellationRequested)return;if(VersionKey(game)==key){game.VersionInfo=result;Save();Render();}Refresh();}catch(OperationCanceledException){}catch(Exception e){info.Text=e.Message;}finally{busy=false;actions.IsEnabled=true;}}
  actions.Children.Add(Btn("Read update notes",()=>{if(ReleaseVersions.SafeLink(game.VersionInfo.ReleaseUrl)){try{Process.Start(new ProcessStartInfo(game.VersionInfo.ReleaseUrl){UseShellExecute=true});}catch(Exception e){info.Text=e.Message;}}else info.Text="No update link found. Check the source or choose the correct publisher feed.";},true));actions.Children.Add(Btn("Check date",async()=>await Check()));actions.Children.Add(Btn("Change source",async()=>{ReleaseSourceDialog(game);await Check();}));actions.Children.Add(Btn("Done",()=>dialog.Close()));
  extra.Children.Add(Btn("Save optional hint",()=>{if(hintToggle.IsChecked==true&&UpdateDates.BuildDate(buildDate.Text)==null){info.Text="Enter a valid, non-future YYYY.MM.DD build date.";return;}game.VersionInfo.CompareBuildDate=hintToggle.IsChecked==true;game.VersionInfo.ConfirmedBuildDate=buildDate.Text.Trim();if(hintToggle.IsChecked==true)game.VersionInfo.ConfirmedReleaseSource=ReleaseVersions.SourceKey(game);Save();Render();Refresh();}));extra.Children.Add(Btn("Version numbers / find version files",()=>VersionDialog(game)));body.Children.Add(new Expander{Header="Optional build-date and version comparison",Content=extra,Margin=new Thickness(0,18,0,0),Foreground=Brush("#BAB5C4")});Refresh();dialog.Loaded+=async(_,_)=>{if(dialogProbe==null)await Check();};dialog.ShowDialog();
 }
}
