using System;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using Playdeck.Core;
namespace Playdeck;
public sealed partial class MainWindow {
 void ManualVersionEntry(Game game){var body=new StackPanel();body.Children.Add(Text("YOUR GAME'S VERSION",26,"#76DDD3"));body.Children.Add(Text("Copy the installed version from the game's main menu or About screen. Only add a latest version when you have checked a reliable source.",13,"#B7B1C0"));body.Children.Add(Text("INSTALLED VERSION",12));var installed=new TextBox{Text=game.VersionInfo.InstalledBuild.Length==0?game.VersionInfo.Installed:"",Margin=new Thickness(0,8,0,18)};body.Children.Add(installed);body.Children.Add(Text("LATEST VERSION · OPTIONAL",12));var latest=new TextBox{Text=game.VersionInfo.ManualLatest,Margin=new Thickness(0,8,0,18)};body.Children.Add(latest);var hint=Text("An empty latest version keeps the card neutral. Your entry never becomes a Steam build ID.",12,"#B7B1C0");body.Children.Add(hint);var dialog=Dialog("Enter version",body,620);body.Children.Add(Btn("Save version",()=>{if(string.IsNullOrWhiteSpace(installed.Text)||installed.Text.Length>120||latest.Text.Length>120){hint.Text="Enter an installed version; each label must be at most 120 characters.";return;}var snapshot=JsonSerializer.Deserialize<Game>(JsonSerializer.Serialize(game,Store.Json),Store.Json)!;snapshot.VersionInfo.Mode="Manual";snapshot.VersionInfo.ManualVersion=installed.Text.Trim();snapshot.VersionInfo.ManualLatest=latest.Text.Trim();snapshot.VersionInfo.ManualLatestAt=latest.Text.Trim().Length>0?DateTimeOffset.UtcNow:null;game.VersionInfo=GameVersions.ReadLocal(snapshot);Save();Render();dialog.Close();},true));body.Children.Add(Btn("Cancel",()=>dialog.Close()));dialog.ShowDialog();}

 void VersionDialog(Game game){
  var body=new StackPanel();body.Children.Add(Text("LET'S FIND YOUR VERSION",27,"#E1FF46"));body.Children.Add(Text(game.Name,22));
  var intro=Text("Find local evidence, confirm the right source, and keep track of what needs an update. Unknown versions stay neutral until there is a valid comparison.",13,"#BAB5C4");intro.Margin=new Thickness(0,12,0,18);body.Children.Add(intro);
  var summary=Text(VersionDescription(game.VersionInfo),13);body.Children.Add(new Border{Background=Brush("#29272F"),CornerRadius=new CornerRadius(14),Padding=new Thickness(18),Child=summary});
  var caption=Text("01 / VERSION EVIDENCE",19,"#76DDD3",FontWeights.Black);caption.Margin=new Thickness(0,20,0,10);body.Children.Add(caption);
  var evidence=new ListBox{Height=110,Background=Brush("#222225"),Foreground=Brush("#ECEAE6"),BorderThickness=new Thickness(0),DisplayMemberPath="Label",FontSize=14};body.Children.Add(evidence);
  var detail=Text("Looks near this game and in known Steam / Epic installation records. No recursive drive scan.",12,"#A9A3B2");detail.Margin=new Thickness(0,10,0,12);body.Children.Add(detail);evidence.SelectionChanged+=(_,_)=>{if(evidence.SelectedItem is VersionEvidence e)detail.Text=e.Path+"\nConfirm this agrees with the version shown inside your game.";};
  var automatic=new CheckBox{Content="Keep this game checked daily when Playdeck opens",IsChecked=game.VersionInfo.CheckedAt==null||game.VersionInfo.AutoCheck,Margin=new Thickness(0,8,0,14)};body.Children.Add(automatic);
  var actions=new WrapPanel();body.Children.Add(actions);var dialog=Dialog("Find version · "+game.Name,body,760);using var stop=CancellationTokenSource.CreateLinkedTokenSource(lifetime.Token);dialog.Closed+=(_,_)=>stop.Cancel();bool busy=false;
  async Task Scan(){if(busy)return;busy=true;actions.IsEnabled=false;detail.Text="Looking for small version files and installed launcher records…";try{var snapshot=JsonSerializer.Deserialize<Game>(JsonSerializer.Serialize(game,Store.Json),Store.Json)!;var found=await Task.Run(()=>VersionDiscovery.Find(snapshot,stop:stop.Token),stop.Token);if(stop.IsCancellationRequested)return;evidence.ItemsSource=found;detail.Text=found.Count==0?"No reliable file found. Use Enter version and copy the version shown in the game's main menu or About screen.":$"Found {found.Count} source(s). Select one, then Use selected. Executable versions may belong to the engine.";if(found.Count>0)evidence.SelectedIndex=0;}catch(OperationCanceledException){}catch(Exception e){detail.Text="Could not read the files: "+e.Message;}finally{busy=false;actions.IsEnabled=true;}}
  async Task Apply(bool selected){if(busy)return;if(selected&&evidence.SelectedItem is not VersionEvidence){detail.Text="Select a source first, or enter the version yourself.";return;}busy=true;actions.IsEnabled=false;try{var snapshot=JsonSerializer.Deserialize<Game>(JsonSerializer.Serialize(game,Store.Json),Store.Json)!;string key=VersionKey(game);snapshot.VersionInfo.AutoCheck=automatic.IsChecked==true;if(selected&&evidence.SelectedItem is VersionEvidence e){snapshot.VersionInfo.Mode=e.Kind=="Steam"?"Automatic":e.Kind;snapshot.VersionInfo.EvidencePath=e.Kind=="File"?e.Path:"";if(e.Kind=="Steam"){snapshot.SteamId=e.AppId;snapshot.VersionInfo.ManifestPath=e.Path;}else snapshot.VersionInfo.ManifestPath="";}
   summary.Text="Checking your selected source…";var info=await versions.Check(snapshot,root,library.Online,stop.Token);if(stop.IsCancellationRequested||VersionKey(game)!=key)return;game.VersionInfo=info;if(info.AppId>0&&info.InstalledBuild.Length>0)game.SteamId=info.AppId;Save();Render();summary.Text=VersionDescription(info);detail.Text=info.Detail;
  }catch(OperationCanceledException){}catch(Exception e){summary.Text="Check unavailable: "+e.Message;}finally{busy=false;actions.IsEnabled=true;}}
  actions.Children.Add(Btn("Find version files",async()=>await Scan()));actions.Children.Add(Btn("Use selected",async()=>await Apply(true),true));actions.Children.Add(Btn("Check saved source",async()=>await Apply(false)));
  actions.Children.Add(Btn("Enter version",()=>{ManualVersionEntry(game);summary.Text=VersionDescription(game.VersionInfo);automatic.IsChecked=game.VersionInfo.CheckedAt==null||game.VersionInfo.AutoCheck;}));actions.Children.Add(Btn("Choose Steam game",()=>{ChooseSteamMatch(game);summary.Text=VersionDescription(game.VersionInfo);}));actions.Children.Add(Btn("Advanced",()=>{AdvancedVersionDialog(game);summary.Text=VersionDescription(game.VersionInfo);}));actions.Children.Add(Btn("Done",()=>dialog.Close()));
  body.Children.Add(Text("Green = a matching recent comparison. Yellow = a newer version found. Grey = needs your help or a fresh check. Manual comparisons use the latest version you entered; Steam builds compare only with the same Steam branch.",12,"#B7B0C0"));
  dialog.Loaded+=async(_,_)=>{if(dialogProbe==null)await Scan();};dialog.ShowDialog();
 }
}
